# Generated by Django 4.2.3 on 2023-08-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
